services:
  - type: web
    name: laboratorio12-apis-jenifer
    runtime: web
    buildCommand: ""
    startCommand: "php -S 0.0.0.0:$PORT index.php"
    plan: free
    envVars:
      - key: WEATHER_API_KEY
        sync: false
        